# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FV6Vp-R6dhF3yTRn05ETIew8jrDLEAFk
"""

import json
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox

class Book:
    def __init__(self,id,title,genre,author,price):
        self.id = id
        self.title = title
        self.genre = genre
        self.author = author
        self.price = price

    def __str__(self):
        return f"{self.id} | {self.title} | {self.genre} | {self.author} | {self.price}"

    def to_dict(self):
      return {
            "ID": self.id,
            "Title": self.title,
            "Genre": self.genre,
            "Author": self.author,
            "Price": self.price

        }

class Gui:
    def __init__(self, json):
        self.json = json

        root = tk.Tk()
        root.title("Books")
        root.geometry("500x400")

        self.combo = ttk.Combobox(root, values=["Title", "Genre", "Author", "Price"])
        self.combo.set("Title")
        self.combo.pack()

        label_search = tk.Label(root, text="Search")
        label_search.pack()

        self.entry_search = tk.Entry(root)
        self.entry_search.pack()

        srchBtn = tk.Button(root, text="Search", command=self.submit)
        srchBtn.pack()

        addBtn = tk.Button(root, text="Add",command=self.add_window)
        addBtn.pack()

        upBtn = tk.Button(root, text="Update",command=self.update_window)
        upBtn.pack()

        delBtn = tk.Button(root, text="Delete", command=self.delete)
        delBtn.pack()

        self.listbox = tk.Listbox(root, width=50)
        self.listbox.pack()

        root.mainloop()

    def submit(self):
        usrInput = self.entry_search.get()
        cat = self.combo.get()
        SrchRe = self.json.search(cat,usrInput)

        self.listbox.delete(0, tk.END)
        for book in SrchRe:
            self.listbox.insert(tk.END, f"{book['ID']} | {book['Title']}| {book['Genre']} | {book['Author']} | {book['Price']}")

    def add_window(self):
        self.window = tk.Toplevel()
        self.window.title("Add Book")
        self.window.geometry("500x400")

        idLabel = tk.Label(self.window, text="ID")
        idLabel.pack()
        self.entry_id = tk.Entry(self.window)
        self.entry_id.pack()

        titlabel = tk.Label(self.window, text="Title")
        titlabel.pack()
        self.entry_title = tk.Entry(self.window)
        self.entry_title.pack()

        genLabel = tk.Label(self.window, text="Genre")
        genLabel.pack()
        self.entry_Genre = tk.Entry(self.window)
        self.entry_Genre.pack()

        AuthLabel = tk.Label(self.window, text="Author")
        AuthLabel.pack()
        self.entry_Auth = tk.Entry(self.window)
        self.entry_Auth.pack()

        prcLabel = tk.Label(self.window, text="Price")
        prcLabel.pack()
        self.entry_price = tk.Entry(self.window)
        self.entry_price.pack()

        addBtn = tk.Button(self.window, text="Add", command=self.add_submit)
        addBtn.pack()


    def add_submit(self):
      book = Book(self.entry_id.get(),self.entry_title.get(),self.entry_Genre.get(),self.entry_Auth.get(),self.entry_price.get())
      self.json.add(book)
      self.window.destroy()

    def update_window(self):
        self.listbox.curselection()
        self.window = tk.Toplevel()
        self.window.title("Update Book")

        self.window.geometry("500x400")

        self.update_combo = ttk.Combobox(self.window, values=["Title", "Genre", "Author", "Price"])
        self.update_combo.set("Title")
        self.update_combo.pack()

        label_update = tk.Label(self.window, text="Update")
        label_update.pack()

        self.entry_update = tk.Entry(self.window)
        self.entry_update.pack()

        upBtn = tk.Button(self.window, text="Update", command=self.update_submit)
        upBtn.pack()

    def update_submit(self):
      selected = self.listbox.get(tk.ACTIVE)
      if not selected:
         return

      book_id = selected.split(" | ")[0]
      cat = self.update_combo.get()

      new_value = self.entry_update.get()
      if new_value == "":
          messagebox.showerror("fel", "Tomt fält")
          return

      if cat == "Price":
          if not new_value.isdigit():
              messagebox.showerror("Fel", "Price måste vara ett tal!")
              return

      self.json.update(book_id, cat, new_value)

      self.window.destroy()


    def delete(self):
      selected = self.listbox.get(tk.ACTIVE)
      if not selected:
         return

      book_id = selected.split(" | ")[0]

      self.json.delete(book_id)



class Json:
    def __init__(self, filename):
        self.filename = filename
        with open(self.filename, "r") as f:
            self.books = json.load(f)

    def search(self, category, query):
        result = []
        for book in self.books:
          if query.lower() in str(book[category]).lower():
              result.append(book)
        return result


    def add(self, book):
      self.books.append(book.to_dict())
      self.save()


    def save(self):
      with open(self.filename, "w") as f:
        json.dump(self.books,f, indent=4)


    def update(self, book_id, category, input_value):
        for book in self.books:
              if book["ID"] == book_id:
                  book[category] = input_value
                  self.save()
                  return

    def delete(self,book_id):
      for book in self.books:
        if book["ID"] == book_id:
            self.books.remove(book)
            self.save()

def main():
    data = Json("books.json")
    Gui(data)

if __name__ == "__main__":
    main()

